openapi: 3.0.1
info:
  title: API de Categoria
  description: API para gerenciar categorias de um sistema.
  version: 1.0.0
  contact:
    name: Seu Nome
    email: seuemail@dominio.com
    url: https://seusite.com

servers:
  - url: http://localhost:8080/api
    description: Servidor de Desenvolvimento

paths:
  /categorias:
    get:
      summary: Lista todas as categorias
      operationId: listarCategorias
      tags:
        - Categoria
      responses:
        '200':
          description: Lista de categorias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoriaDTO'
    post:
      summary: Cria uma nova categoria
      operationId: criarCategoria
      tags:
        - Categoria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaInput'
      responses:
        '201':
          description: Categoria criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaDTO'

  /categorias/{id}:
    get:
      summary: Obtém uma categoria pelo ID
      operationId: obterCategoria
      tags:
        - Categoria
      parameters:
        - name: id
          in: path
          description: ID da categoria
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Categoria encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaDTO'
        '404':
          description: Categoria não encontrada

    put:
      summary: Atualiza uma categoria existente
      operationId: atualizarCategoria
      tags:
        - Categoria
      parameters:
        - name: id
          in: path
          description: ID da categoria
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaInput'
      responses:
        '200':
          description: Categoria atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaDTO'
        '404':
          description: Categoria não encontrada

    delete:
      summary: Remove uma categoria pelo ID
      operationId: removerCategoria
      tags:
        - Categoria
      parameters:
        - name: id
          in: path
          description: ID da categoria
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Categoria removida com sucesso
        '404':
          description: Categoria não encontrada

components:
  schemas:
    CategoriaDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: "Categoria 1"
    CategoriaInput:
      type: object
      properties:
        nome:
          type: string
          example: "Categoria Nova"
      required:
        - nome
